### ISSUE TITLE
Add role version in Ansible Galaxy

### ISSUE THREAD

**Issue by hongbo-miao** [hurricanehrndz/ansible-rustup#33]
It would be great to set role version in Ansible Galaxy at

https://galaxy.ansible.com/ui/standalone/roles/hurricanehrndz/rustup/versions/

So that we can set versions in requirements.yml like

```
---
collections:
  - name: community.general
    version: 7.5.0
roles:
  - name: bartdorlandt.poetry
    version: 0.1.5
  - name: staticdev.pyenv
    version: 2.10.1]
```

to help the role behavior more predictable.

Thank you! ☺️

**Comment by hurricanehrndz** [comment]
Well this is on maintenance since I really don't use ansible anymore

**Comment by hurricanehrndz** [comment]
But sure

**Comment by hongbo-miao** [comment]
Thanks @hurricanehrndz ! I didn't realize this repo is in maintenance mode. Appreciate for help!

i also just found I can do

```yaml
- name: Install common packages
  hosts: my-server
  tasks:
    - name: Install common packages using Snap (classic)
      become: true
      community.general.snap:
        name:
          - rustup
        state: present
        classic: true
    - name: Set up Rust stable toolchain
      command: rustup default stable
```

Hopefully it can help some future people as another option 😃
