### ISSUE TITLE
Install doesn't work for distros not listed in vars folder (default.yml not found)

### ISSUE THREAD

**Issue by dive-deeper** [hurricanehrndz/ansible-rustup#8]
I used this role without a problem under Ubuntu but was having problems in OpenSuse Tumbleweed. I noticed this piece of code:

```yaml
- name: Set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml
```

However there's no `default.yml`. I think `vars/main.yml` is supposed to be this file. I renamed it and added the standard content (gcc, make, curl) and it worked. So either rename main.yml into default.yml  and add some default content, or change the value within "with_first_found".

Thanks for this role. Cheers.
